version: '3.4'

services:
  app:
    image: app
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn nodemon -q -L -w src src/main.ts
